# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/zesty64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 8888, host: 8888

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    
    # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    echo '' >> /etc/ssh/sshd_config
    echo 'KexAlgorithms diffie-hellman-group1-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1' >> /etc/ssh/sshd_config
    sudo service ssh restart
    echo ubuntu:12345|sudo chpasswd

    sudo apt-get update
    sudo apt-get -y install git python3 python-virtualenv
    git clone https://stefansommer@bitbucket.org/stefansommer/theanogeometry.git

    cd theanogeometry
    virtualenv -p python3 . 
    source bin/activate
    pip install numpy scipy theano jupyter matplotlib multiprocess sklearn

    echo '[global] floatX = float64' >> ~/.theanorc 
    echo 'device = cpu' >> ~/.theanorc 
    echo 'optimizer = fast_run' >> ~/.theanorc 
    echo 'cast_policy = numpy+floatX' >> ~/.theanorc 
    mkdir ~/.jupyter
    cat > ~/.jupyter/jupyter_notebook_config.json <<- EOF
{
  "NotebookApp": {
    "password": "sha1:1c72c9b695f9:eb46afba98397e1dc22b1f048ce7dc944f55a8bd"
  }
}
EOF
  SHELL

  config.vm.provision "shell", :run => 'always', inline: <<-SHELL
    cd theanogeometry
    source bin/activate
    pip install --upgrade numpy scipy theano jupyter matplotlib multiprocess sklearn

    git pull

    export OMP_NUM_THREADS=1; jupyter notebook --allow-root &
  SHELL
end
